# Generated by Django 5.0.3 on 2024-05-09 13:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField()),
                ('offer_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_usage_limit', models.PositiveIntegerField(default=0, help_text='Total number of times the coupon can be used')),
                ('limit_per_user', models.PositiveIntegerField(default=1, help_text='Maximum number of times a single user can use the coupon')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required to use the coupon', max_digits=10)),
                ('maximum_offer_price', models.DecimalField(decimal_places=2, default=0, help_text='Maximum discount amount offered by the coupon', max_digits=10)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Total number of times the coupon has been used')),
            ],
        ),
    ]
