# Generated by Django 5.0.3 on 2024-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='maximum_offer_price',
        ),
        migrations.AddField(
            model_name='coupon',
            name='maximum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum order amount required to use the coupon', max_digits=10),
        ),
    ]
