# Generated by Django 5.0.3 on 2024-05-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0002_remove_coupon_maximum_offer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
