# Generated by Django 5.0.3 on 2024-05-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0003_coupon_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
