# Generated by Django 5.0.3 on 2024-04-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
