# Generated by Django 5.0.3 on 2024-04-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand_is_deleted_type_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
