# Generated by Django 5.0.3 on 2024-03-29 05:30

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='age',
            field=models.PositiveIntegerField(validators=[store.models.validate_age_within_range]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[store.models.validate_price_within_range]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='proof',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[store.models.validate_proof_within_range]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(validators=[store.models.validate_stock_within_range]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[store.models.validate_volume_within_range]),
        ),
    ]
