# Generated by Django 5.0.3 on 2024-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_reactivated',
            field=models.BooleanField(default=False),
        ),
    ]
