# Generated by Django 5.0.3 on 2024-05-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_coupon_code_cart_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_wishlist',
        ),
    ]
