# Generated by Django 5.0.3 on 2024-05-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('online_payment', 'Online Payment'), ('wallet', 'Wallet')], default='cash_on_delivery', max_length=50),
        ),
    ]
