# Generated by Django 5.0.3 on 2024-05-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='returned',
            field=models.BooleanField(choices=[(False, 'Not Returned'), (True, 'Returned')], default=False),
        ),
    ]
